services:
  frontend-movies:
    build:
      context: ./frontend-movies
      dockerfile: Dockerfile
    container_name: frontend-movies
    environment:
      API_BACKEND_URL: http://host.docker.internal:8080/api
    ports:
      - "8080:80"
    volumes:
      - ./frontend-movies:/var/www/html
    depends_on:
      - db-movies
      - db-actors

  db-movies:
    image: postgres:16
    container_name: db-movies
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: app_root_password
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_pass
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"
    volumes:
      - ./api-movies/sql/local:/docker-entrypoint-initdb.d

  db-actors:
    image: postgres:16
    container_name: db-actors
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: app_root_password
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_pass
      POSTGRES_DB: actors_db
    ports:
      - "5433:5433"
    volumes:
      - ./api-actors/sql/local:/docker-entrypoint-initdb.d