services:
  frontend-movies:
    build:
      context: ./frontend-movies
      dockerfile: Dockerfile
    container_name: frontend-movies
    environment:
      API_BACKEND_URL: http://host.docker.internal:8080/api 
    ports:
      "8080:80"
    volumes:
      ./frontend-movies:/var/www/html
    depends_on:
      - db-movies
      - db-actors

  db-movies:
    image: PostgreSQL 
    container_name: db-movies
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: app_root_password
      MYSQL_USER: movies-user
      MYSQL_PASSWORD: movies-pass
      MYSQL_DATABASE: movies
    ports:
      - "5432:5432"
    volumes:
      - ./api-movies/sql/:/docker-entrypoint-initdb.d

  db-actors:
    image: mariadb:10.6
    container_name: db-actors
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: app_root_password
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: stranger
    ports:
      - "3306:3306"
    volumes:
      - ./backend/sql/mariadb:/docker-entrypoint-initdb.d
    
build:
  context: ./frontend-movies
  dockerfile: Dockerfile