spring.application.name=actors-api
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate

spring.profiles.active=local

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/actors_db
spring.datasource.username=movies_user
spring.datasource.password=movies_pass