spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=movies_user
spring.datasource.password=movies_pass
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true